package com.finsecseal.common.domain;

public enum ExecutionEventType {
    RUN_STARTED,
    MODEL_REQUEST,
    MODEL_RESPONSE,
    TOOL_PROPOSED,
    POLICY_EVALUATED,
    TOOL_REQUEST,
    TOOL_RESPONSE,
    SANDBOX_STATE_CHANGED,
    ORACLE_EVALUATED,
    FINDING_CREATED,
    RUN_COMPLETED,
    RUN_CANCEL_REQUESTED,
    RUN_FAILED,
    BUDGET_UPDATED,
    CONTRACT_APPROVED,
    RELEASE_INVALIDATED,
    ATTESTATION_GENERATED,
    DEMO_RESET,
    EVENT_GAP
}
